# trivy.yaml
vulnerability:
  vex:
    - ./.vex/vex.json # Path to your VEX file relative to the repo root
  show-suppressed: true # Set to 'true' to see suppressed findings in SARIF
  severity:
    - CRITICAL
    - HIGH
    - MEDIUM
    - LOW
  ignore-unfixed: false # Ignore unfixed vulnerabilities

# --- REMOVE THESE LINES ---
# report:
#   format: json # Output format for the report
#   output: trivy-results.json # Output file name for the json report
# --- END REMOVAL ---

# Note: "exit code" should be "exit-code" for Trivy CLI (like in the workflow's uses action).
# For consistency, you can change it here or rely on the action's exit-code parameter.
# Since we are using raw CLI here, we won't pass exit-code to the config file
# as it's typically a CLI flag.
# exit-code: 0 # This line can also be removed from trivy.yaml
