exit-code: 0

vulnerability:
  vex-path: vex.json
  show-suppressed: true # Set to 'true' to see suppressed findings in SARIF
  severity:
    - CRITICAL
    - HIGH
    - MEDIUM
    - LOW

  ignore-unfixed: false
