exit-code: 0

vulnerability:
  vex-path:
    - ../../vex.json # Path to your VEX file relative to the repo root
  show-suppressed: true # Set to 'true' to see suppressed findings in SARIF
  severity:
    - CRITICAL
    - HIGH
    - MEDIUM
    - LOW

  ignore-unfixed: false # Ignore unfixed vulnerabilities

