name: Build Docker Image

on:
  push:
    branches: "**"

permissions:
  contents: read # Required to checkout the code
  actions: read # Required for the action to run properly

jobs:
  build:
    name: Build an image from Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: localbuild/TrivyAppTest:latest
