name: Security Scan with VEX

on:
  push:
    branches: "**"

permissions:
  contents: read # Required to checkout the code
  security-events: write # Required to upload SARIF results to GitHub Security tab
  actions: read # Required for the action to run properly

jobs:
  trivy_scan:
    name: "Trivy Vulnerability Scan"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx for caching"
        uses: docker/setup-buildx-action@v3

      - name: "Build Docker image with cache"
        uses: docker/build-push-action@v5
        with:
          context: .
          # Load the image into the local Docker daemon
          load: true
          # A tag is required for the trivy-action to reference the image
          tags: localbuild/trivyapptest:latest
          # Enable caching to speed up subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Run Trivy scan with VEX filter"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "localbuild/trivyapptest:latest"
          format: "sarif"
          output: "trivy-results.sarif"

          trivy-config: ".github/trivy/trivy.yaml"

      - name: "Upload Trivy scan results to Security tab"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
