# SecScanVex.yml
name: Trivy Scan with VEX

on:
  push:
    branches: "**"

permissions:
  contents: read # Required to checkout the code
  security-events: write # Required to upload SARIF results to GitHub Security tab
  actions: read # Required for the action to run properly

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t localbuild/trivyapptest:latest .

      - name: Create VEX directory (local files)
        run: |
          mkdir -p .vex
          cp vex.json .vex/

      - name: Run Trivy CLI for JSON Output (Debugging PURL)
        run: |
          docker run --rm \
            -v "$PWD":/github/workspace \
            aquasecurity/trivy:latest \  # <--- CHANGED THIS LINE
            image --config-file /github/workspace/.github/trivy/trivy.yaml \
            --format json \
            --output trivy-results.json \
            --severity CRITICAL,HIGH,MEDIUM,LOW \
            --ignore-unfixed \
            localbuild/trivyapptest:latest

      # SARIF upload step should remain commented out for this debugging phase
      # - name: Upload Trivy scan results to GitHub Security tab
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v3
      # with:
      #   sarif_file: "trivy-results.sarif"
      # category: "trivy-vex-scan"

      - name: Upload Raw Trivy JSON Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-json-results
          path: trivy-results.json
          if-no-files-found: error
