name: Trivy SARIF Scan

on:
  push:
    branches:
      - "**"

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  trivy-sarif:
    runs-on: ubuntu-latest
    name: Trivy scan (SARIF for GitHub Security)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trivy scan (SARIF output)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH,MEDIUM,LOW
          format: sarif
          output: trivy-report.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif
