name: Vulnerability Report

on:
  push:
    branches:
      - "**"

  # workflow_dispatch:
  # schedule:
  #   - cron: "0 2 * * *" # every day at 2 AM UTC

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    name: Scan for vulnerabilities using Trivy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs # File system scan
          severity: CRITICAL,HIGH,MEDIUM,LOW,INFO # Set the severity levels to scan
          scan-ref: .
          format: sarif
          output: trivy-report.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-report.sarif
